name: Update Job Listings

on:
  schedule:
    # Run every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]
    paths: 
      - 'src/**'
      - '.github/workflows/update-jobs.yml'

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
    
    - name: Install and verify dependencies
      run: |
        echo "Python version and location:"
        python --version
        which python
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        echo "Installed packages:"
        python -m pip list
        echo "Python path:"
        python -c "import sys; print('\n'.join(sys.path))"
        echo "Verifying installations:"
        python -c "import jobspy; print('✅ jobspy imported successfully')"
        python -c "import pandas; print('✅ pandas version:', pandas.__version__)"
        python -c "import tabulate; print('✅ tabulate version:', tabulate.__version__)"
    
    - name: Run job scraper
      run: |
        python src/main.py
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code README.md || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update job listings - $(date '+%Y-%m-%d %H:%M:%S')"
        git push 